kipoi/models

Divergent430/TransferLearning/model.yaml
just updating model description
=> Update Divergent430TransferLearning model descrip

Basenji/dataloader.py, Basset/dataloader.py, CpGenie/template/dataloader.py, DeepSEA/template/dataloader.py, DeepSEAKeras/dataloader.py, lsgkm-SVM/template/dataloader.py, pwm_HOCOMOCO/human/template/dataloader.py, rbp_eclip/template/dataloader.py
- closes https://github.com/kipoi/models/issues/67
=> enable linecache for all the models

Basenji/model.yaml
Added more detail about inputs and outputs of the model. The information came from the answers provided from [this issue](https://github.com/calico/basenji/issues/16) on basenji's repo.
=> Update model.yaml docs

shared/envs/kipoi-py3-keras1.2.yaml, shared/envs/kipoi-py3-keras2.yaml, shared/envs/models.yaml
- add Optimus_5prime to common environments
- add kipoi_interpret to common environments
=> add Optimus_5prime to common envs

CpGenie/merged/model.yaml, CpGenie/model-template.yaml
- Decreasing test precision decimals since model almost  yields correct results on [circleci](https://circleci.com/gh/kipoi/models/692)
```
Model predictions don't match the expected predictions.expected: [[6.3271570e-01 4.5703515e-02 4.6448010e-01 6.6644096e-01 6.6531360e-01
1.7037481e-02 5.4933724e-04 5.2473855e-01 3.1782594e-08 1.0779649e-08
6.0925031e-01 5.8502084e-01 7.5778329e-01 5.4477721e-01 4.0703183e-01
1.4397803e-02 2.3542672e-01 3.6448280e-06 6.2314487e-01 5.8552611e-01
1.8952161e-28 2.2147678e-10 6.9853920e-01 7.0070374e-01 8.0339953e-02
2.9868675e-02 7.2089177e-01 2.6059796e-03 4.8255655e-01 3.3769084e-08
2.7212763e-04 6.0298854e-01 6.7038029e-01 7.3680513e-02 2.8450689e-08
6.7153138e-01 5.3199714e-01 5.2635658e-01 6.7327201e-01 6.5665323e-01
6.8430483e-01 6.5270644e-01 …
```
=> CpGenie test:

CpGenie/merged/model.yaml, CpGenie/model-template.yaml, deepTarget/dataloader.yaml, deepTarget/model.yaml
[WIP] try to fix nightly builds
=> [WIP] exact pinning

KipoiSplice/4/dataloader.yaml, KipoiSplice/4cons/dataloader.yaml
Deepdish is not used by KipoiSplice
=> Remove deepdish dependency from KipoiSplice

KipoiSplice/4/dataloader.yaml, KipoiSplice/4cons/dataloader.yaml
* Update dataloader.yaml
* Update dataloader.yaml
* Update dataloader.yaml
* Update dataloader.yaml
=> Remove deepdish dependency from KipoiSplice (#149)

DeepSEA/predict/model.yaml, DeepSEA/variantEffects/model.yaml
=> less precise

shared/envs/kipoi-py3-keras1.2.yaml, shared/envs/kipoi-py3-keras2.yaml
Dependencies changed:
- added pip to dependencies
- pinning python to 3.6
=> Dependencies

MMSplice/modules/acceptor/model.yaml
=> changed precision_decimal

BPNet-OSKN/model.yaml, FactorNet/CEBPB/meta_Unique35_DGF/model.yaml, rbp_eclip/model-template.yaml
=> Fix keras updates

DeepMEL/dataloader.py, DeepMEL/dataloader.yaml, DeepMEL/model.yaml
=> Added DeepMEL model.

BPNet-OSKN/model.yaml
Also tested the predict_example snippet
Closes: #218
=> kipoi env create BPNet-OSKN works now

.circleci/config.yml, SeqVec/embedding/model.yaml, SeqVec/embedding2structure/model.yaml, SeqVec/structure/model.yaml
=> Fix seqvec

SeqVec/embedding2structure/model.yaml
As discussed, I removed  dataloader from SeqVec/embedding2structure
=> Remove dataloader from SeqVec/embedding2structure

Xpresso/model-template.yaml
Thanks Ziga :)
All the discussions are here  - https://github.com/kipoi/models/pull/224
=> Fixed Xpresso

DeepSEA/beluga/model.yaml
Closes https://github.com/kipoi/kipoi/issues/579
=> Add variant scoring to DeepSEA/beluga

.circleci/config.yml, .circleci/setup.sh
Closes: #252 
Example run: [Here](https://app.circleci.com/pipelines/github/kipoi/models/730/workflows/8826ff3c-6be4-463b-8932-377025b8831f)
PS: I moved test_common_env out of the main jo, otherwise it would be executed 4 times.
With access to only 4 concurrent jobs, the runtime reduced to 48 mins from ~3.5 hours.
=> Parallelized CI

.circleci/config.yml, .circleci/setup.sh, Xpresso/model-template.yaml
Includes fixes from: #https://github.com/kipoi/kipoi-utils/pull/32 and https://github.com/kipoi/kipoiseq/pull/98
=> Added default arguments to Xpresso's yaml representation

.circleci/config.yml, SeqVec/test_subset.txt
Original problem #251 
However, with the machine executor which has more RAM than the docker instance  it seems to be working fine.
=> Add seqvec back to ci

KipoiSplice/4/dataloader.yaml, KipoiSplice/4cons/dataloader.yaml
I had to downgrade python version to 3.5 since pyvcf does not seem to be getting compiled with pyvcf
=> Fixed kipoisplice

APARENT/README.md, APARENT/site_probabilities/dataloader.py, APARENT/site_probabilities/dataloader.yaml, APARENT/site_probabilities/model.py, APARENT/site_probabilities/model.yaml, APARENT/veff/dataloader.py, APARENT/veff/dataloader.yaml, APARENT/veff/model.py, APARENT/veff/model.yaml
Add the APA Regression Net (APARENT) model for DNA sequence scoring and variant effect prediction.
This branch depends on the following pull request in kipoiseq:
https://github.com/kipoi/kipoiseq/pull/100
=> Add APARENT model

.circleci/config.yml
Unfortunately this solution is dependent on the network speed. I am not exactly sure how to go around this.
=> Increased parallelism to avoid build timeout error

DeepSTARR/model.yaml
Add the DeepSTARR model for DNA sequence prediction of enhancer activities.
Zenodo: https://doi.org/10.5281/zenodo.5502060
Code: https://github.com/bernardo-de-almeida/DeepSTARR/tree/main/DeepSTARR
Manuscript: https://www.biorxiv.org/content/10.1101/2021.10.05.463203
=> Added DeepSTARR

APARENT/site_probabilities/dataloader.yaml, APARENT/site_probabilities/model.yaml, APARENT/veff/dataloader.yaml, APARENT/veff/model.py, APARENT/veff/model.yaml
- Fix mistake in proximal and distal score index
- Implement adjustable isoform window in model
=> Adjust APARENT model

shared/containers/model-to-singularity.json
Automatic pr created from kipoi-containers
=> Update container jsons

APARENT/veff/dataloader.yaml, APARENT/veff/model.yaml
- Change python version + pinning
- Mark `vcf_file_tbi` as optional
=> Aparent update

.circleci/config.yml
Replacing installation of singularity from conda to released apptainer binary. Nothing else need to be changed since apptainer is maintaining singularity interface for now.
=> Add apptainer

TREDNet/phase_one/model.py, TREDNet/phase_one/model.yaml, TREDNet/phase_two_HepG2/model.py, TREDNet/phase_two_HepG2/model.yaml, TREDNet/phase_two_K562/model.py, TREDNet/phase_two_K562/model.yaml, TREDNet/phase_two_islet/model.py, TREDNet/phase_two_islet/model.yaml
Hi, I would like to add the DL models of our recent paper to the Kipoi database. Hope all goes through well. Please feel free to reach out to me if I've got anything wrong. 
The models passed all the tests described in Getting Started page.
=> First attempt at adding TREDNet model

shared/containers/model-to-singularity.json
Updating singularity containers
=> Updated container json

a2z-chromatin/model-template.yaml, a2z-chromatin/models.tsv
Hello Kipoi maintainers,
I'd like to add my plant leaf chromatin accessibility and DNA methylation models to Kipoi. They are currently only published as a [preprint](https://doi.org/10.1101/2021.11.11.468292) but the manuscript has been accepted and I'll update the cite DOIs when that is actually out.
Cheers,
Travis
=> Add a2z-chromatin models

a2z-chromatin/model-template.yaml, shared/envs/models.yaml
- Added test prediction for a2z-chromatin/a2z-accessibility
- Pinned pip
- Added a2z-chromatin to kipoi-py3-keras2-tf2
=> Few additional changes for a2z-chromatin

TREDNet/phase_one/model.yaml, TREDNet/phase_two_HepG2/model.yaml, TREDNet/phase_two_K562/model.yaml, TREDNet/phase_two_islet/model.yaml
- Updated version of the models TREDNet/phase_two_HepG2 TREDNet/phase_two_K562
=> TREDNet model updates

TREDNet/phase_one/model.yaml, TREDNet/phase_two_HepG2/model.yaml, TREDNet/phase_two_K562/model.yaml, TREDNet/phase_two_islet/model.yaml
(This is for testing)
This reverts commit c59c66783ebb25975f12378ff123aad09aaf31c5, reversing changes made to 7e314550d26e6eee8d37d45874738eb8389a09c3.
=> Revert "Merge pull request #363 from okurman/master"

DeepLiver/DeepLiver_Accessibility/dataloader.py, DeepLiver/DeepLiver_Accessibility/dataloader.yaml, DeepLiver/DeepLiver_Accessibility/model.yaml, DeepLiver/DeepLiver_Accessibility/tf_keras_model.py, DeepLiver/DeepLiver_Activity/dataloader.py, DeepLiver/DeepLiver_Activity/dataloader.yaml, DeepLiver/DeepLiver_Activity/model.yaml, DeepLiver/DeepLiver_Activity/tf_keras_model.py, DeepLiver/DeepLiver_Zonation/dataloader.py, DeepLiver/DeepLiver_Zonation/dataloader.yaml, DeepLiver/DeepLiver_Zonation/model.yaml, DeepLiver/DeepLiver_Zonation/tf_keras_model.py, DeepLiver/LICENSE.txt
Hi!
I would like to add the DeepLiver models to the zoo. You can find the preprint describing the models at https://www.biorxiv.org/content/10.1101/2022.12.08.519575v1 
Since I built the model using the internal keras from tensorflow (keras=2.2.4-tf, tensorflow=1.15), I had to add my own model class. It is exactly the same as kipoi's KerasModel, but using tensorflow.keras instead of keras for the imports.
Local tests have been successful, let me know if more information is needed!
C
=> DeepLiver models

BPNet_Dmel_OreR_2to3hr_ZDTBCG/model.py, BPNet_Dmel_OreR_2to3hr_ZDTBCG/model.yaml
Upon final submission to Dev Cell, (https://www.biorxiv.org/content/10.1101/2022.12.20.520743v1) adding Kipoi for BPNet on the 6 TFs in OreR fly embryos.
=> Update: Uploaded BPNet ZDTBCG model

APARENT/veff/dataloader.yaml, APARENT/veff/model.yaml
=> Freeze `APARENT/veff` deps
